/** Core + long-tail terms for SEO and answer-engine optimization */
export const seoKeywords = [
  "Revel",
  "AI product strategist",
  "product strategy tool",
  "website audit AI",
  "UX audit",
  "product blindspots",
  "growth gaps",
  "product roadmap generator",
  "AI website analysis",
  "competitor analysis tool",
  "messaging audit",
  "product experience review",
  "founder tools",
  "indie hacker product review",
  "Reveal Index",
  "product blueprint",
  "action queue",
  "export product roadmap",
  "markdown export roadmap",
  "OKX AI agent",
  "agent to MCP",
  "A2MCP",
  "BlindspotLab",
  "tryrevel",
  "SaaS product audit",
  "conversion optimization audit",
  "onboarding audit",
  "landing page audit",
  "product-led growth",
  "prioritized improvements",
  "answer engine optimization",
  "AI product audit tool",
  "website UX analysis",
  "product messaging review",
  "startup product strategy",
  "SaaS growth audit",
  "landing page review tool",
  "product discovery AI",
  "MCP agent tools",
] as const;

export const pageKeywords: Record<string, string[]> = {
  home: ["AI product analysis", "find growth gaps", "product strategist"],
  "how-it-works": ["how Revel works", "product analysis steps", "AI audit workflow"],
  features: ["product analysis features", "UX review", "Reveal Index", "Blueprint"],
  pricing: ["Revel pricing", "free product audit", "SaaS pricing"],
  faq: ["Revel FAQ", "AI audit questions", "product analysis help"],
  about: ["BlindspotLab", "Mojeeb Titilayo", "about Revel"],
  docs: ["Revel documentation", "API reference", "getting started"],
  "sample-reports": ["sample product audit", "example Revel report"],
  contact: ["contact Revel", "BlindspotLab support"],
};