/** Canonical public URLs for sitemap, IndexNow, and crawler discovery */
export const publicSitemapPaths = [
  "/",
  "/features",
  "/compare",
  "/pricing",
  "/guides/find-product-blindspots",
  "/about",
  "/contact",
  "/partners",
  "/docs",
  "/docs/getting-started",
  "/docs/how-it-works",
  "/docs/api",
  "/docs/partners",
  "/docs/integrations",
  "/docs/mcp",
  "/docs/ecosystem",
  "/docs/faq",
  "/docs/sample-reports",
  "/privacy",
  "/terms",
  "/llms.txt",
  "/llms-full.txt",
  "/ai.txt",
] as const;

export type PublicSitemapPath = (typeof publicSitemapPaths)[number];

export const sitemapPriorities: Record<
  PublicSitemapPath,
  { changeFrequency: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never"; priority: number }
> = {
  "/": { changeFrequency: "weekly", priority: 1 },
  "/features": { changeFrequency: "monthly", priority: 0.9 },
  "/compare": { changeFrequency: "monthly", priority: 0.9 },
  "/pricing": { changeFrequency: "monthly", priority: 0.85 },
  "/guides/find-product-blindspots": {
    changeFrequency: "monthly",
    priority: 0.8,
  },
  "/about": { changeFrequency: "monthly", priority: 0.8 },
  "/contact": { changeFrequency: "yearly", priority: 0.6 },
  "/partners": { changeFrequency: "monthly", priority: 0.8 },
  "/docs": { changeFrequency: "monthly", priority: 0.85 },
  "/docs/getting-started": { changeFrequency: "monthly", priority: 0.85 },
  "/docs/how-it-works": { changeFrequency: "monthly", priority: 0.85 },
  "/docs/api": { changeFrequency: "monthly", priority: 0.8 },
  "/docs/partners": { changeFrequency: "monthly", priority: 0.85 },
  "/docs/integrations": { changeFrequency: "monthly", priority: 0.8 },
  "/docs/mcp": { changeFrequency: "monthly", priority: 0.85 },
  "/docs/ecosystem": { changeFrequency: "monthly", priority: 0.8 },
  "/docs/faq": { changeFrequency: "monthly", priority: 0.85 },
  "/docs/sample-reports": { changeFrequency: "monthly", priority: 0.85 },
  "/privacy": { changeFrequency: "yearly", priority: 0.3 },
  "/terms": { changeFrequency: "yearly", priority: 0.3 },
  "/llms.txt": { changeFrequency: "weekly", priority: 0.7 },
  "/llms-full.txt": { changeFrequency: "weekly", priority: 0.65 },
  "/ai.txt": { changeFrequency: "weekly", priority: 0.65 },
};