import type { AnalysisReport } from "@/types/analysis";

export function exportToMarkdown(report: AnalysisReport, website: string): string {
  const lines: string[] = [
    `# Revel Blueprint`,
    ``,
    `**Website:** ${website}`,
    `**Reveal Index:** ${report.score}/100`,
    ``,
    `## Summary`,
    report.summary,
    ``,
    `## Blindspots`,
    ``,
  ];

  for (const bs of report.blindspots) {
    lines.push(
      `### ${bs.title}`,
      `- **Priority:** ${bs.priority}`,
      `- **Category:** ${bs.category}`,
      `- **Issue:** ${bs.description}`,
      `- **Fix:** ${bs.suggestedFix}`,
      ``
    );
  }

  lines.push(`## Blueprint`, ``);

  for (const step of report.blueprint) {
    lines.push(
      `### Step ${step.step}: ${step.title}`,
      `- **Effort:** ${step.estimatedEffort}`,
      `- **Impact:** ${step.expectedImpact}`,
      `- ${step.description}`,
      ``
    );
  }

  lines.push(`## Action Queue`, ``);

  for (const action of report.actions) {
    lines.push(
      `### ${action.title}`,
      `- **Priority:** ${action.priority}`,
      `- **Effort:** ${action.estimatedEffort}`,
      `- **Outcome:** ${action.expectedOutcome}`,
      `- ${action.description}`,
      ``
    );
  }

  lines.push(`---`, `Generated by Revel. Reveal what others miss.`);

  return lines.join("\n");
}

export function exportToJson(report: AnalysisReport, website: string): string {
  return JSON.stringify(
    {
      website,
      generatedAt: new Date().toISOString(),
      ...report,
    },
    null,
    2
  );
}

/** GitHub-flavored markdown — paste into issues/PRs or download. */
export function exportToGitHubMarkdown(
  report: AnalysisReport,
  website: string
): string {
  const lines: string[] = [
    `# Revel Blueprint`,
    ``,
    `> Website: ${website} · Reveal Index: **${report.score}/100**`,
    ``,
    report.summary,
    ``,
    `## Blindspots`,
    ``,
  ];

  for (const bs of report.blindspots) {
    lines.push(
      `### ${bs.title}`,
      `- **Priority:** \`${bs.priority}\` · **Category:** \`${bs.category}\``,
      ``,
      bs.description,
      ``,
      `**Suggested fix:** ${bs.suggestedFix}`,
      ``
    );
  }

  lines.push(`## Blueprint`, ``);

  for (const step of report.blueprint) {
    lines.push(
      `${step.step}. **${step.title}** (${step.estimatedEffort}, ${step.expectedImpact} impact)`,
      `   ${step.description}`,
      ``
    );
  }

  lines.push(`## Action Queue`, ``);

  for (const action of report.actions) {
    lines.push(
      `- [ ] **${action.title}** — \`${action.priority}\` · ${action.estimatedEffort}`,
      `  - ${action.description}`,
      `  - _Expected:_ ${action.expectedOutcome}`,
      ``
    );
  }

  lines.push(
    `---`,
    `_Generated by [Revel](https://tryrevel.xyz) Mission Control_`
  );

  return lines.join("\n");
}