import { normalizeAnalysisReport } from "@/lib/report-schema";
import type { AnalysisReport } from "@/types/analysis";

function safeReport(report: AnalysisReport | unknown): AnalysisReport {
  return normalizeAnalysisReport(report);
}

export function exportToMarkdown(
  report: AnalysisReport | unknown,
  website: string
): string {
  const r = safeReport(report);
  const lines: string[] = [
    `# Revel Blueprint`,
    ``,
    `**Website:** ${website}`,
    `**Reveal Index:** ${r.score}/100`,
    ``,
    `## Summary`,
    r.summary,
    ``,
    `## Blindspots`,
    ``,
  ];

  if (r.blindspots.length === 0) {
    lines.push(`_No blindspots recorded._`, ``);
  } else {
    for (const bs of r.blindspots) {
      lines.push(
        `### ${bs.title}`,
        `- **Priority:** ${bs.priority}`,
        `- **Category:** ${bs.category}`,
        `- **Issue:** ${bs.description}`,
        `- **Fix:** ${bs.suggestedFix}`,
        ``
      );
    }
  }

  lines.push(`## Blueprint`, ``);

  if (r.blueprint.length === 0) {
    lines.push(`_No blueprint steps recorded._`, ``);
  } else {
    for (const step of r.blueprint) {
      lines.push(
        `### Step ${step.step}: ${step.title}`,
        `- **Effort:** ${step.estimatedEffort}`,
        `- **Impact:** ${step.expectedImpact}`,
        `- ${step.description}`,
        ``
      );
    }
  }

  lines.push(`## Action Queue`, ``);

  if (r.actions.length === 0) {
    lines.push(`_No actions recorded._`, ``);
  } else {
    for (const action of r.actions) {
      lines.push(
        `### ${action.title}`,
        `- **Priority:** ${action.priority}`,
        `- **Effort:** ${action.estimatedEffort}`,
        `- **Outcome:** ${action.expectedOutcome}`,
        `- ${action.description}`,
        ``
      );
    }
  }

  lines.push(`---`, `Generated by Revel. Reveal what others miss.`);

  return lines.join("\n");
}

export function exportToJson(
  report: AnalysisReport | unknown,
  website: string
): string {
  const r = safeReport(report);
  return JSON.stringify(
    {
      website,
      generatedAt: new Date().toISOString(),
      ...r,
    },
    null,
    2
  );
}

/** GitHub-flavored markdown for issues/PRs or download. */
export function exportToGitHubMarkdown(
  report: AnalysisReport | unknown,
  website: string
): string {
  const r = safeReport(report);
  const lines: string[] = [
    `# Revel Blueprint`,
    ``,
    `> Website: ${website} · Reveal Index: **${r.score}/100**`,
    ``,
    r.summary,
    ``,
    `## Blindspots`,
    ``,
  ];

  if (r.blindspots.length === 0) {
    lines.push(`_No blindspots recorded._`, ``);
  } else {
    for (const bs of r.blindspots) {
      lines.push(
        `### ${bs.title}`,
        `- **Priority:** \`${bs.priority}\` · **Category:** \`${bs.category}\``,
        ``,
        bs.description,
        ``,
        `**Suggested fix:** ${bs.suggestedFix}`,
        ``
      );
    }
  }

  lines.push(`## Blueprint`, ``);

  if (r.blueprint.length === 0) {
    lines.push(`_No blueprint steps recorded._`, ``);
  } else {
    for (const step of r.blueprint) {
      lines.push(
        `${step.step}. **${step.title}** (${step.estimatedEffort}, ${step.expectedImpact} impact)`,
        `   ${step.description}`,
        ``
      );
    }
  }

  lines.push(`## Action Queue`, ``);

  if (r.actions.length === 0) {
    lines.push(`_No actions recorded._`, ``);
  } else {
    for (const action of r.actions) {
      lines.push(
        `- [ ] **${action.title}** - \`${action.priority}\` · ${action.estimatedEffort}`,
        `  - ${action.description}`,
        `  - _Expected:_ ${action.expectedOutcome}`,
        ``
      );
    }
  }

  lines.push(
    `---`,
    `_Generated by [Revel](https://tryrevel.xyz) Mission Control_`
  );

  return lines.join("\n");
}
