import type { Metadata } from "next";
import Link from "next/link";
import { Navbar } from "@/components/landing/navbar";
import { Footer } from "@/components/landing/footer";
import { PageSeo } from "@/components/seo/page-seo";
import { getOkxAuditPriceUsd } from "@/lib/billing/okx-x402";
import { createPageMetadata } from "@/lib/seo/metadata";
import { siteConfig } from "@/lib/site-config";

const title = "Terms of Service";
const description =
  "Terms of service for using Revel, including Mission Control, Partner API, and optional Linear, Notion, and GitHub export connections.";

export const metadata: Metadata = createPageMetadata({
  title,
  description,
  path: "/terms",
  keywords: ["terms of service", "Revel terms", "BlindspotLab"],
});

export default function TermsPage() {
  const auditPrice = getOkxAuditPriceUsd();

  return (
    <>
      <PageSeo title={title} description={description} path="/terms" />
      <Navbar />
      <main className="mx-auto max-w-2xl px-6 py-32">
        <h1 className="font-heading text-4xl font-semibold">Terms of Service</h1>
        <p className="mt-4 text-muted">Last updated: July 10, 2026</p>

        <div className="mt-12 space-y-8 text-muted">
          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Service description
            </h2>
            <p className="mt-3 leading-relaxed">
              Revel provides AI-powered website and product experience analysis,
              including the Reveal Index, blindspot map, Blueprint roadmap, and
              Action Queue. Results are generated by AI and should be reviewed by
              a human before implementation. Revel is available via Mission
              Control (web app), Partner API, MCP/A2MCP endpoints, and the OKX.AI
              agent marketplace. Optional export features let you download
              reports or, if you connect third-party accounts, push content into
              tools you authorize.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Acceptable use
            </h2>
            <ul className="mt-3 list-disc space-y-2 pl-5 leading-relaxed">
              <li>
                Analyze only websites you own or have explicit permission to
                audit.
              </li>
              <li>
                Do not use Revel to scrape, attack, overload, or abuse
                third-party services.
              </li>
              <li>
                Do not share Partner API keys in client-side code or public
                repositories.
              </li>
              <li>
                Do not misrepresent Revel scores or reports as human consulting
                or guaranteed outcomes.
              </li>
              <li>
                Only connect Linear, Notion, or GitHub accounts you are
                authorized to use, and only export data you are allowed to store
                in those workspaces.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Mission Control usage limits
            </h2>
            <p className="mt-3 leading-relaxed">
              Signed-in users receive 3 free product audits per week (resets
              Monday 00:00 UTC) during early access. Admin accounts may have
              unlimited access. Rate limits apply to prevent abuse.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Export integrations (Linear, Notion, GitHub)
            </h2>
            <p className="mt-3 leading-relaxed">
              Downloadable exports (Markdown, JSON, GitHub-flavored Markdown)
              are provided for your local use. Cloud exports to Linear, Notion,
              or GitHub Gist require you to complete OAuth authorization with
              that provider. By connecting an integration you grant Revel
              permission to act in your account solely to create the export you
              request, using the scopes disclosed during authorization and in
              our{" "}
              <Link href="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
            <ul className="mt-3 list-disc space-y-2 pl-5 leading-relaxed">
              <li>
                <strong className="text-foreground">Your workspace:</strong>{" "}
                Content is created under your Linear team, Notion workspace, or
                GitHub account — not in a shared multi-tenant BlindspotLab
                destination that other Revel customers can browse.
              </li>
              <li>
                <strong className="text-foreground">Your responsibility:</strong>{" "}
                You control sharing inside Linear, Notion, and GitHub after
                export. We are not responsible for access you grant there or for
                those providers&apos; availability or policies.
              </li>
              <li>
                <strong className="text-foreground">Revocation:</strong> You may
                disconnect integrations in Mission Control or revoke access in
                the third-party product at any time. We store connection tokens
                encrypted at rest and delete them when you disconnect.
              </li>
              <li>
                <strong className="text-foreground">No guarantee of third-party
                compliance:</strong>{" "}
                Export success depends on your permissions, granted OAuth scopes,
                and the third-party API. Insufficient permissions may cause
                export to fail.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Partner API
            </h2>
            <p className="mt-3 leading-relaxed">
              Approved platforms may integrate Revel via the Partner API subject
              to separate approval, API key terms, and billing mode (whitelisted,
              trial, or prepaid credits). Partners are responsible for securing
              API keys, displaying insights appropriately to their users, and
              complying with applicable laws. Revel insights displayed through
              partner platforms are read-only recommendations — partners must not
              automatically modify user content based on Revel output without
              explicit user action.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              OKX.AI marketplace &amp; payments
            </h2>
            <p className="mt-3 leading-relaxed">
              Paid audits via OKX.AI or x402 billing are charged per successful
              audit (currently ${auditPrice.toFixed(2)} USDT0 on X Layer unless
              otherwise stated). Payments are processed through OKX Onchain OS
              and the Agent Payments Protocol. Refund and dispute policies for
              on-chain payments follow OKX and marketplace rules. Revel does not
              custody user funds.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Intellectual property
            </h2>
            <p className="mt-3 leading-relaxed">
              Revel, BlindspotLab, Reveal Index, and related branding are owned
              by BlindspotLab. You retain ownership of URLs and content you
              submit. Generated reports are licensed to you for internal business
              use and export. Partner integrations may display Revel scores and
              insights within their products per approved API terms.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Disclaimer
            </h2>
            <p className="mt-3 leading-relaxed">
              Revel provides strategic recommendations, not legal, financial, or
              investment advice. AI output may contain errors. BlindspotLab does
              not guarantee improved business outcomes from following Revel
              suggestions.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Limitation of liability
            </h2>
            <p className="mt-3 leading-relaxed">
              To the maximum extent permitted by law, BlindspotLab is not liable
              for indirect, incidental, or consequential damages arising from use
              of Revel, Partner API, marketplace integrations, or third-party
              export destinations (Linear, Notion, GitHub). Our total liability
              is limited to fees you paid to Revel in the twelve months preceding
              the claim.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Changes
            </h2>
            <p className="mt-3 leading-relaxed">
              We may update these terms as Revel adds features (Partner API,
              ecosystem integrations, billing, export providers). Material
              changes will be reflected in the &quot;Last updated&quot; date
              above.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Contact
            </h2>
            <p className="mt-3 leading-relaxed">
              Questions? Email{" "}
              <a
                href={`mailto:${siteConfig.organization.email}`}
                className="text-primary hover:underline"
              >
                {siteConfig.organization.email}
              </a>{" "}
              or visit our{" "}
              <Link href="/contact" className="text-primary hover:underline">
                contact page
              </Link>
              .
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
