import type { Metadata } from "next";
import Link from "next/link";
import { Navbar } from "@/components/landing/navbar";
import { Footer } from "@/components/landing/footer";
import { PageSeo } from "@/components/seo/page-seo";
import { createPageMetadata } from "@/lib/seo/metadata";

const title = "Terms of Service";
const description =
  "Terms of service for using Revel, the AI product strategist by BlindspotLab.";

export const metadata: Metadata = createPageMetadata({
  title,
  description,
  path: "/terms",
  keywords: ["terms of service", "Revel terms", "BlindspotLab"],
});

export default function TermsPage() {
  return (
    <>
      <PageSeo title={title} description={description} path="/terms" />
      <Navbar />
      <main className="mx-auto max-w-2xl px-6 py-32">
        <h1 className="font-heading text-4xl font-semibold">Terms of Service</h1>
        <p className="mt-4 text-muted">Last updated: July 3, 2026</p>

        <div className="mt-12 space-y-8 text-muted">
          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Service description
            </h2>
            <p className="mt-3 leading-relaxed">
              Revel provides AI-powered website analysis and strategic product
              recommendations. Analysis results are generated by AI and should be
              reviewed by a human before implementation.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Acceptable use
            </h2>
            <p className="mt-3 leading-relaxed">
              You may only analyze websites you own or have permission to analyze.
              Do not use Revel to scrape, attack, or abuse third-party services.
              Rate limits apply to ensure fair usage.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Subscriptions and billing
            </h2>
            <p className="mt-3 leading-relaxed">
              Paid plans are billed monthly through Stripe. You may cancel at any
              time. Refunds are handled on a case-by-case basis.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Limitation of liability
            </h2>
            <p className="mt-3 leading-relaxed">
              Revel provides recommendations, not guarantees. BlindspotLab is not
              liable for business decisions made based on Revel&apos;s analysis.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              Contact
            </h2>
            <p className="mt-3 leading-relaxed">
              Questions? Visit our{" "}
              <Link href="/contact" className="text-primary hover:underline">
                contact page
              </Link>
              .
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}